# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/physicsbook',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/physicsbook',
                'lib_path': 'physicsbook'},
  'syms': {'physicsbook.core': {'physicsbook.core.foo': ('core.html#foo', 'physicsbook/core.py')}}}
